apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: {{ .Values.service.port }}
      protocol: TCP
      name: http

  selector:
    app: {{ .Chart.Name }}